# Generated by Django 4.2.29 on 2026-03-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the doctor', max_length=255, verbose_name='Doctor Name')),
                ('contact_no', models.CharField(help_text='Contact number of the doctor', max_length=20, verbose_name='Contact Number')),
                ('email', models.EmailField(help_text='Email address of the doctor', max_length=254, verbose_name='Email Address')),
                ('highest_qualification', models.CharField(help_text='Highest qualification of the doctor', max_length=255, verbose_name='Highest Qualification')),
                ('specialization', models.CharField(help_text='Specialization of the doctor', max_length=255, verbose_name='Specialization')),
                ('years_of_experience', models.IntegerField(help_text='Years of experience of the doctor')),
            ],
        ),
    ]
