# Generated by Django 4.2.30 on 2026-07-22 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_no', models.CharField(help_text='Contact number of the doctor', max_length=20, verbose_name='Contact Number')),
                ('highest_qualification', models.CharField(help_text='Highest qualification of the doctor', max_length=255, verbose_name='Highest Qualification')),
                ('specialization', models.CharField(help_text='Specialization of the doctor', max_length=255, verbose_name='Specialization')),
                ('years_of_experience', models.IntegerField(default=0, help_text='Years of experience of the doctor')),
            ],
            options={
                'abstract': False,
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='Compounder',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_no', models.CharField(help_text='Contact number of the compounder', max_length=20, verbose_name='Contact Number')),
                ('qualification', models.CharField(blank=True, help_text='Qualification / Certification (e.g., D.Pharm, B.Pharm)', max_length=255, verbose_name='Qualification')),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night'), ('Full Day', 'Full Day')], default='Full Day', help_text='Assigned work shift', max_length=20)),
                ('is_head_compounder', models.BooleanField(default=False, help_text='Designates whether this is the head compounder')),
                ('assigned_doctor', models.ForeignKey(blank=True, help_text='Assigned doctor in the clinic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compounders', to='doctor.doctor')),
            ],
            options={
                'abstract': False,
            },
            bases=('user.user',),
        ),
    ]
