# Generated by Django 4.2.30 on 2026-07-23 02:13

from django.db import migrations, models
import doctor.models
import utils.storages


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile photo of the doctor', null=True, storage=utils.storages.DoctorPhotoStorage(), upload_to=doctor.models.doctor_photo_upload_path, verbose_name='Doctor Photo'),
        ),
    ]
