# Generated by Django 4.2.30 on 2026-08-09 09:54

from django.db import migrations, models
import doctor.models
import utils.storages


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='signature',
            field=models.ImageField(blank=True, help_text='Signature image of the doctor', null=True, storage=utils.storages.DoctorSignatureStorage(), upload_to=doctor.models.doctor_signature_upload_path, verbose_name='Doctor Signature'),
        ),
    ]
