# Generated by Django 4.2.29 on 2026-03-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comorbidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the comorbidity', max_length=255, verbose_name='Comorbidity Name')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name of the patient', max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Last name of the patient', max_length=255, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(help_text='Date of birth of the patient', verbose_name='Date of Birth')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Sex of the patient', max_length=1, verbose_name='Sex')),
                ('contact_no', models.CharField(help_text='Contact number of the patient', max_length=20, verbose_name='Contact Number')),
                ('email', models.EmailField(help_text='Email address of the patient', max_length=254, verbose_name='Email Address')),
                ('type', models.CharField(choices=[('Regular', 'Regular'), ('Free', 'Free')], help_text='Type of the patient', max_length=10, verbose_name='Type')),
                ('date_registered', models.DateField(auto_now_add=True, help_text='Date when the patient was registered', verbose_name='Date Registered')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood group of the patient', max_length=3, verbose_name='Blood Group')),
                ('family_history', models.TextField(blank=True, help_text='Family medical history of the patient', null=True, verbose_name='Family History')),
                ('known_allergies', models.TextField(blank=True, help_text='Known allergies of the patient', null=True, verbose_name='Known Allergies')),
                ('smokes', models.BooleanField(help_text='Whether the patient smokes or not', verbose_name='Smokes')),
                ('alcohololic', models.BooleanField(help_text='Whether the patient is an alcoholic or not', verbose_name='Alcoholic')),
                ('comorbidities', models.ManyToManyField(blank=True, help_text='Comorbidities of the patient', to='patient.comorbidity', verbose_name='Comorbidities')),
                ('patient', models.OneToOneField(help_text='Patient associated with the medical information', on_delete=django.db.models.deletion.CASCADE, to='patient.patientprofile', verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_file_number', models.CharField(help_text='Internal file number for the patient', max_length=20, unique=True, verbose_name='Internal File Number')),
                ('external_file_number', models.CharField(blank=True, help_text='External file number for the patient', max_length=20, null=True, unique=True, verbose_name='External File Number')),
                ('patient', models.OneToOneField(help_text='Patient associated with the file record', on_delete=django.db.models.deletion.CASCADE, to='patient.patientprofile', verbose_name='Patient')),
            ],
        ),
    ]
