# Generated by Django 4.2.30 on 2026-07-22 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comorbidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the comorbidity', max_length=255, verbose_name='Comorbidity Name')),
            ],
        ),
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_file_number', models.CharField(help_text='Internal file number for the patient', max_length=20, unique=True, verbose_name='Internal File Number')),
                ('external_file_number', models.CharField(blank=True, help_text='External file number for the patient', max_length=20, null=True, unique=True, verbose_name='External File Number')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(help_text='e.g., Rheumatoid Arthritis, SLE', max_length=255)),
                ('state', models.CharField(choices=[('Active', 'Active'), ('Remission', 'Remission'), ('Stable', 'Stable'), ('Worsening', 'Worsening')], default='Active', max_length=50)),
                ('version_note', models.TextField(blank=True, help_text="Doctor's notes for this specific version of diagnosis", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Patient Diagnosis',
                'verbose_name_plural': 'Patient Diagnosis History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth of the patient', null=True, verbose_name='Date of Birth')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Sex of the patient', max_length=1, verbose_name='Sex')),
                ('contact_no', models.CharField(blank=True, help_text='Contact number of the patient', max_length=20, verbose_name='Contact Number')),
                ('type', models.CharField(choices=[('Regular', 'Regular'), ('Free', 'Free')], default='Regular', help_text='Type of the patient', max_length=10, verbose_name='Type')),
                ('date_registered', models.DateField(auto_now_add=True, help_text='Date when the patient was registered', verbose_name='Date Registered')),
            ],
            options={
                'abstract': False,
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='PatientState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('awaiting_query', 'Awaiting Query')], default='idle', help_text='Current WhatsApp conversation state', max_length=20, verbose_name='State')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_started_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.OneToOneField(help_text='Current WhatsApp conversation state for the patient', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_state', to='patient.patientprofile', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Patient State',
                'verbose_name_plural': 'Patient States',
            },
        ),
        migrations.CreateModel(
            name='PatientQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text="Patient's query or concern", verbose_name='Patient Query')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether the query has been resolved or not', verbose_name='Is Resolved')),
                ('ai_generated_response', models.TextField(blank=True, help_text="AI generated response to the patient's query", null=True, verbose_name='AI Generated Response')),
                ('is_ai_response_approved', models.BooleanField(default=False, help_text='Whether the AI generated response has been approved by a doctor', verbose_name='Is AI Response Approved')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='patient.patientprofile')),
            ],
            options={
                'verbose_name': 'Patient Query',
                'verbose_name_plural': 'Patient Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood group of the patient', max_length=3, verbose_name='Blood Group')),
                ('family_history', models.TextField(blank=True, help_text='Family medical history of the patient', null=True, verbose_name='Family History')),
                ('known_allergies', models.TextField(blank=True, help_text='Known allergies of the patient', null=True, verbose_name='Known Allergies')),
                ('smokes', models.BooleanField(help_text='Whether the patient smokes or not', verbose_name='Smokes')),
                ('alcohololic', models.BooleanField(help_text='Whether the patient is an alcoholic or not', verbose_name='Alcoholic')),
                ('comorbidities', models.ManyToManyField(blank=True, help_text='Comorbidities of the patient', to='patient.comorbidity', verbose_name='Comorbidities')),
                ('patient', models.OneToOneField(help_text='Patient associated with the medical information', on_delete=django.db.models.deletion.CASCADE, to='patient.patientprofile', verbose_name='Patient')),
            ],
        ),
    ]
