# Generated by Django 4.2.29 on 2026-03-29 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(help_text='e.g., Rheumatoid Arthritis, SLE', max_length=255)),
                ('state', models.CharField(choices=[('Active', 'Active'), ('Remission', 'Remission'), ('Stable', 'Stable'), ('Worsening', 'Worsening')], default='Active', max_length=50)),
                ('version_note', models.TextField(blank=True, help_text="Doctor's notes for this specific version of diagnosis", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_records', to='treatment.consultation')),
                ('joints_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.jointspain')),
                ('patient_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_history', to='patient.patientprofile')),
                ('rumat_diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.rumatdiagnosis')),
            ],
            options={
                'verbose_name': 'Patient Diagnosis',
                'verbose_name_plural': 'Patient Diagnosis History',
                'ordering': ['-created_at'],
            },
        ),
    ]
