# Generated by Django 4.2.30 on 2026-07-22 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdiagnosis',
            name='consultation_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_records', to='treatment.consultation'),
        ),
        migrations.AddField(
            model_name='patientdiagnosis',
            name='joints_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.jointspain'),
        ),
        migrations.AddField(
            model_name='patientdiagnosis',
            name='patient_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_history', to='patient.patientprofile'),
        ),
        migrations.AddField(
            model_name='patientdiagnosis',
            name='rumat_diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.rumatdiagnosis'),
        ),
        migrations.AddField(
            model_name='filerecord',
            name='patient',
            field=models.OneToOneField(help_text='Patient associated with the file record', on_delete=django.db.models.deletion.CASCADE, to='patient.patientprofile', verbose_name='Patient'),
        ),
    ]
