# Generated by Django 4.2.30 on 2026-08-09 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientmedicalinfo',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='patientmedicalinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this medical info record was created', null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalinfo',
            name='patient',
            field=models.ForeignKey(help_text='Patient associated with the medical information', on_delete=django.db.models.deletion.CASCADE, related_name='medical_info_history', to='patient.patientprofile', verbose_name='Patient'),
        ),
    ]
