# Generated by Django 4.2.30 on 2026-04-18 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patientdiagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text="Patient's query or concern", verbose_name='Patient Query')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether the query has been resolved or not', verbose_name='Is Resolved')),
                ('ai_generated_response', models.TextField(blank=True, help_text="AI generated response to the patient's query", null=True, verbose_name='AI Generated Response')),
                ('is_ai_response_approved', models.BooleanField(default=False, help_text='Whether the AI generated response has been approved by a doctor', verbose_name='Is AI Response Approved')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='patient.patientprofile')),
            ],
            options={
                'verbose_name': 'Patient Query',
                'verbose_name_plural': 'Patient Queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
