# Generated by Django 4.2.30 on 2026-04-18 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patientqueries'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('awaiting_query', 'Awaiting Query')], default='idle', help_text='Current WhatsApp conversation state', max_length=20, verbose_name='State')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_started_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.OneToOneField(help_text='Current WhatsApp conversation state for the patient', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_state', to='patient.patientprofile', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Patient State',
                'verbose_name_plural': 'Patient States',
            },
        ),
    ]
