# Generated by Django 4.2.30 on 2026-08-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patientmedicalinfo_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientmedicalinfo',
            old_name='alcohololic',
            new_name='alcoholic',
        ),
    ]
