# Generated by Django 4.2.30 on 2026-07-23 02:13

from django.db import migrations, models
import django.db.models.deletion
import utils.storages
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(help_text='Address Line 1', max_length=255, verbose_name='Address Line 1')),
                ('line2', models.CharField(blank=True, help_text='Address Line 2', max_length=255, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(help_text='City', max_length=255, verbose_name='City')),
                ('state', models.CharField(help_text='State', max_length=255, verbose_name='State')),
                ('country', models.CharField(help_text='Country', max_length=255, verbose_name='Country')),
                ('zip_code', models.CharField(help_text='Zip Code', max_length=20, verbose_name='Zip Code')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the clinic', max_length=255, verbose_name='Clinic Name')),
                ('logo', models.ImageField(help_text='Logo of the clinic', storage=utils.storages.ClinicLogoStorage(), upload_to='clinic_logos/', verbose_name='Clinic Logo')),
                ('contact_email', models.EmailField(help_text='Contact email for the clinic', max_length=254, verbose_name='Contact Email')),
                ('contact_number', models.CharField(help_text='Contact number for the clinic', max_length=20, verbose_name='Contact Number')),
                ('clinic_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this clinic installation', unique=True)),
                ('api_access_token', models.CharField(blank=True, help_text='The secret token provided for AI service', max_length=255, null=True, verbose_name='AI Service Token')),
                ('is_ai_enabled', models.BooleanField(default=False, help_text='Status of the AI extraction service')),
                ('address', models.OneToOneField(help_text='Address of the clinic', on_delete=django.db.models.deletion.CASCADE, to='clinic.address', verbose_name='Clinic Address')),
            ],
            options={
                'verbose_name_plural': 'Clinic Settings',
            },
        ),
    ]
