# Generated by Django 4.2.29 on 2026-04-05 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicsettings',
            options={'verbose_name_plural': 'Clinic Settings'},
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='api_access_token',
            field=models.CharField(blank=True, help_text='The secret token provided for AI service', max_length=255, null=True, verbose_name='AI Service Token'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='clinic_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this clinic installation', null=True),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='is_ai_enabled',
            field=models.BooleanField(default=False, help_text='Status of the AI extraction service'),
        ),
    ]
