# Generated by Django 4.2.29 on 2026-04-05 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_clinicsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsettings',
            name='clinic_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this clinic installation', unique=True),
        ),
    ]
