# Generated by Django 4.2.30 on 2026-07-05 23:19

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_clinicsettings_clinic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsettings',
            name='logo',
            field=models.ImageField(help_text='Logo of the clinic', storage=storages.backends.s3.S3Storage(), upload_to='clinic_logos/', verbose_name='Clinic Logo'),
        ),
    ]
