# Generated by Django 4.2.30 on 2026-07-05 23:23

from django.db import migrations, models
import utils.storages


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_clinicsettings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsettings',
            name='logo',
            field=models.ImageField(help_text='Logo of the clinic', storage=utils.storages.ClinicLogoStorage(), upload_to='clinic_logos/', verbose_name='Clinic Logo'),
        ),
    ]
