# Generated by Django 4.2.30 on 2026-07-23 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(choices=[('DOCTOR', 'Doctor'), ('COMPOUNDER', 'Compounder'), ('PATIENT', 'Patient'), ('ALL', 'All Staff / General')], db_index=True, default='ALL', help_text='Role for whom this notification is intended (e.g. Doctor, Compounder)', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message_json', models.JSONField(blank=True, default=dict)),
                ('notification_type', models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('LAB_REPORT', 'Lab Report'), ('PRESCRIPTION', 'Prescription'), ('SYSTEM', 'System Alert'), ('GENERAL', 'General Info'), ('URGENT', 'Urgent Attention')], db_index=True, default='GENERAL', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, help_text='Optional link to navigate when notification is clicked', max_length=500, null=True)),
                ('is_soft_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag — set true to archive without permanent DB deletion')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='Optional specific user recipient. If null, target_role receives it.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
