# Generated by Django 4.2.30 on 2026-07-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='message_json',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
