# Generated by Django 4.2.29 on 2026-03-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jointspain',
            options={'verbose_name': 'Joint Chart', 'verbose_name_plural': 'Joint Charts'},
        ),
        migrations.AlterModelOptions(
            name='rumatdiagnosis',
            options={'verbose_name': 'RumatDiagnosis', 'verbose_name_plural': 'RumatDiagnosis'},
        ),
        migrations.AlterModelOptions(
            name='vitals',
            options={'verbose_name': 'Vitals', 'verbose_name_plural': 'Vitals'},
        ),
    ]
