# Generated by Django 4.2.29 on 2026-03-29 13:01

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_alter_jointspain_options_and_more'),
    ]

    operations = [
        VectorExtension(),
    ]
