# Generated by Django 4.2.30 on 2026-07-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_auto_20260329_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='pain_scale',
            field=models.PositiveIntegerField(blank=True, help_text='Patient pain scale from 0 to 100', null=True, verbose_name='Pain Scale (0-100)'),
        ),
    ]
