# Generated by Django 4.2.30 on 2026-07-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0004_vitals_pain_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumatdiagnosis',
            name='description_t',
            field=models.TextField(blank=True, null=True, verbose_name='Description_total'),
        ),
    ]
