# Generated by Django 4.2.30 on 2026-07-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0005_alter_rumatdiagnosis_description_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Test Name')),
                ('is_common', models.BooleanField(default=False, verbose_name='Is Common Test')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Lab Test',
                'verbose_name_plural': 'Lab Tests',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribed_tests',
            field=models.ManyToManyField(blank=True, related_name='prescriptions', to='treatment.labtest', verbose_name='Prescribed Tests'),
        ),
    ]
