# Generated by Django 4.2.30 on 2026-07-05 23:19

from django.db import migrations, models
import storages.backends.s3
import treatment.models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0006_labtest_prescription_prescribed_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='report_file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to=treatment.models.lab_report_upload_path),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_pdf',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=treatment.models.prescription_upload_path),
        ),
    ]
