# Generated by Django 4.2.30 on 2026-07-05 23:23

from django.db import migrations, models
import treatment.models
import utils.storages


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0007_alter_labresult_report_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='report_file',
            field=models.FileField(storage=utils.storages.LabReportStorage(), upload_to=treatment.models.lab_report_upload_path),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_pdf',
            field=models.FileField(blank=True, null=True, storage=utils.storages.PrescriptionStorage(), upload_to=treatment.models.prescription_upload_path),
        ),
    ]
