# Generated by Django 4.2.30 on 2026-07-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0008_alter_labresult_report_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='test_date',
            field=models.DateField(blank=True, help_text='The date when the lab report test was conducted', null=True),
        ),
    ]
